travis:
  secure:
    BINSTAR_TOKEN: UIr8//jA8cSMPvTVR8n2IVKIKBfkEmcNHK0gz9YpqO9+Np7LlOW8Z6S9Lbnr0AHDmxiAmCkXkFs1e+YTvWAS/38r8kpoSK96HODC8oXCtcOTOHAIffL2+INRaH8acoxNDLVjw+kzQpOyFdbY1Dh4vx+Bj3flFusi88KgzLB7YUC+U6MYPORy4UwpdVBnJocF9teD3yyx4j9P/xW+3BB9j3HY97WMfT8JTIs410nQIDjC5C/wrZix8Ar6tFhnI4XV4AfNwyrIA0NoKLqMqh2yOO5TXKCdJJgRBRA16bsmYQSiQLaKd7t8RL7oZn5npOXF2p6bF1V5RpnoTW8iwVwWm6r3e3fOSt3fRWKu0Y+CF8REalYlQklQQkvSxKXbiFzv7sr/nuLScZu4vUf7szfYGhHw/SFlM6o+Vn1vCHUTe3mZ2DvjbPuQ9WosIRfgSLnNpWpPxCgewrdP1aU45aklReCqOAnTlkHjRb1kBD9Kiiuerxm3HDVqc8K/Ubc9RtVmQpf6GoAEtU9s1Mwp7NJZwjZCGylCs7VLnljXv2MuR5+9R8gXi7DglQ3E8Fp6mk+yjbnCmhUDDj0CBuc076RBYBW+KiG1ghoD2alAZbyphKpffy5mRUsEGRPk2R29sS+313WpxY6k2+kNt9kf3msVqF0mP54EwF87Gb3pgu0gh74=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
