travis:
  secure:
    BINSTAR_TOKEN: jYXeGMUGQdaxeX7j26FKYQqFjn0V+k+tIGqgSPkFTFclRdvE1eZHwjbPm9PbWnyb94uBBaxBkaCBHq9QndLHaBedxuUHeRF9rP+SSSyN10HctpaYB0QOra/h7401KF4T6HyySdP/xCGppcexnfYPpQho9d2fKmOBOvMf8lnA1WNIqQ7rYAzySRXnmqaF8L7ksxDSgcfgux7bKF6CTrt5FEVk/6RSKrkCru/7/KQAX/NgAm8P44lK7j8LZYliJzVGI9ayRO5FKlti9GG7mR1FdxoI4UaosMlTkIvyJK0sWINWG87s++y4F3eLBWOjlcQja4J3KZVoFcfI+Y/xOLv1KS38q+z8Ra9CLfKopzyjUoXW+7sOWUFl/veP+qz/Av00QmRUxGanchRa/pYdSCenur7Cnk/BQmSVB6uljIrBQDLAVZB/+u5ypbIbhhPUjpBZi3aa5LiF+UUsK4hzpDg74anXliESwNVXrEBxoyLWEc2BlG2CCOwtJgCt39EPQj9xb1MCuSbCsUW8fRqJJV/13wQDWOTPKmFORqStHv401RDo3NyNKbRLOrZVGl+pSb+G1N4OSv7+oqkN9iCLOkZCRCJN82xp3Zdsys8TwJx4nSWiTk+t/6JbCN0QrpXy4xQ35wp5x8HE1Seb0piZdMSEdVs2bqO80VqDwbTzTjoFL+M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
